name: Continous Integration Demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, feature/branch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Set up Java
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          ls -al

      #Runs a set of commands using the runners script
      - name: Run a multi-line script
        run: |
          echo add other actions to build
          echo test, and deploy your project.

      - name: check java version
        run: java -version

      - name: gradle build
        run: gradle build

      - name: gradlew build
        run: ./gradlew build

      - name: check docker
        run: |
          docker -v
          docker

    outputs:
      tag: ${{ steps.checkout.outputs.tag }}
