name: Continous Integration Demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master, feature/branch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Set up Java
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Run Az Command
        run: |
          az account show
          az group list

      - name: Run a multi-line script
        run: |
          ls -al

      #Runs a set of commands using the runners script
      - name: Run a multi-line script
        #Run even if above fail
        if: always()
        run: |
          echo add other actions to build
          echo test, and deploy your project.

      - name: check java version
        run: java -version

      - name: gradle build
        run: gradle build

      # Ensure gradlew has execute permission
      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: gradlew build
        run: ./gradlew build

      - name: check docker
        run: |
          docker -v
          docker

      - name: docker build
        run: |
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/demo-spring:1.0
          docker images -a
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Push Docker Image
#        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/demo-spring:1.0


    outputs:
      tag: ${{ steps.checkout.outputs.tag }}
